load npy from dist...
*************************************************
user config:
vocab_size => 50001
word_dim => 300
r_max_len => 202
u_max_r => 13
i_max_r => 24
train_data_size => 51764
test_data_size => 6471
val_data_size => 6471
user_num => 5543
item_num => 3570
batch_size => 64
print_step => 100
*************************************************
load model: ./checkpoints/backup/DeepCoNN_Digital_Music_data_default_GridBEST.pth
loading test data
2024-11-07 11:51:12.869565: test in the test dataset
loading test data
Ehi, ci sono i dati
2461
2024-11-07 11:51:12.872808: test in the test dataset
Traceback (most recent call last):
  File "/home/ironman/projects/sir_ranking/main.py", line 569, in <module>
    recall, avg_recall, avg_precision, avg_hit_rate, avg_auc, predict_loss, test_mse, test_mae = test_bpr(
                                                                                                 ^^^^^^^^^
  File "/home/ironman/projects/sir_ranking/BPR.py", line 244, in test_bpr
    predict_loss, test_mse, test_mae = predict(model, test_data_loader, opt)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ironman/projects/sir_ranking/main.py", line 231, in predict
    for idx, (test_data, scores) in enumerate(data_loader):
             ^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
